manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  opw_kinematics_geometric_parameters:
    a1: 0.150
    a2: -0.020
    b: 0.0
    c1: 0.450
    c2: 0.610
    c3: 0.660
    c4: 0.080
  opw_kinematics_joint_offsets: [0.0, -1.57079633, 0.0, 0.0, 0.0, 0.0]
  opw_kinematics_joint_sign_corrections: [-1, 1, 1, -1, 1, -1]
  kinematics_solver_timeout: 0.5