# config/controllers.yaml

# ← ОБЯЗАТЕЛЬНО: частота обновления FakeControllerManager, Гц
rate: 50

controller_list:
  - name: fake_manipulator_controller
    type: interpolate        # или via_points / last_point
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6